global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'identity-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['identity:8080']
        labels:
          service: 'identity'

  - job_name: 'property-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['property:8080']
        labels:
          service: 'property'

  - job_name: 'sensor-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sensor:8080']
        labels:
          service: 'sensor'

  - job_name: 'gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:8080']
        labels:
          service: 'gateway'