apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: agrosolutions
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'identity'
        static_configs:
          - targets: ['identity:80']

      - job_name: 'property'
        static_configs:
          - targets: ['property:80']

      - job_name: 'sensor'
        static_configs:
          - targets: ['sensor:80']
