apiVersion: apps/v1
kind: Deployment
metadata:
  name: property
  namespace: agrosolutions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property
  template:
    metadata:
      labels:
        app: property
    spec:
      containers:
      - name: property
        image: agrosolutions/property:latest
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=mssql,1433;Database=PropertyDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
        ports:
        - containerPort: 80