name: AgroSolutions CI/CD

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    # Login Docker Hub
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build + Push Identity
    - name: Build & Push Identity
      run: |
        docker build -t $DOCKER_USER/agrosolutions-identity:latest -f src/Services/AgroSolutions.IdentityService/Dockerfile .
        docker push $DOCKER_USER/agrosolutions-identity:latest

    # Property
    - name: Build & Push Property
      run: |
        docker build -t $DOCKER_USER/agrosolutions-property:latest -f src/Services/AgroSolutions.PropertyService/Dockerfile .
        docker push $DOCKER_USER/agrosolutions-property:latest

    # Sensor
    - name: Build & Push Sensor
      run: |
        docker build -t $DOCKER_USER/agrosolutions-sensor:latest -f src/Services/AgroSolutions.SensorIngestionService/Dockerfile .
        docker push $DOCKER_USER/agrosolutions-sensor:latest

    # Alert
    - name: Build & Push Alert
      run: |
        docker build -t $DOCKER_USER/agrosolutions-alert:latest -f src/Services/AgroSolutions.AlertService/Dockerfile .
        docker push $DOCKER_USER/agrosolutions-alert:latest

    # Gateway
    - name: Build & Push Gateway
      run: |
        docker build -t $DOCKER_USER/agrosolutions-gateway:latest -f src/Services/AgroSolutions.ApiGateway/Dockerfile .
        docker push $DOCKER_USER/agrosolutions-gateway:latest
